In [100]:
'''DATA CLEANING'''

from calendar import day_abbr
import requests
import urllib
import json
import csv
# f = open('Desktop/NextMunch/next-munch/json_files/cuisines.json')
# data = json.load(f)
# print(len(data))
url2 = "https://worldwide-restaurants.p.rapidapi.com/search"

dietary_reqs = ['Vegetarian Friendly', 'Vegan Options', 'Gluten Free Options', 'Halal', 'Kosher']
#2nd page
new_url = "https://api.tripadvisor.com/api/internal/1.14/location/186338/restaurants?base_geocodes_on=citymaps&currency=GBP&is_restaurant_filters_v2=true&lang=en_US&limit=50&offset=50&restaurant_tagcategory_standalone=186338&supports_relevance=true"

headers = {
	"content-type": "application/x-www-form-urlencoded",
	"X-RapidAPI-Key": "3b11ee2336msh5791c275fc5dbc6p11fa37jsn3cafb1ed4e82",
	"X-RapidAPI-Host": "worldwide-restaurants.p.rapidapi.com"
}
restaurant_list = ['restaurants']
address_list= ['address']
category_list = ['category']
cuisine_list = ['cuisine']
dietary_list = ['dietary requirements']
phone_list = ['phone No']
price_list = ['price']
index2 = 0
# temp_list = []
new_list = []

def get_API_values(url, header, index):
    print(index)
    if index == 100:
        f = open('APIvals.csv', 'w')
        for i in range(len(restaurant_list)):
                # string = '{'
                if i == 0:
                    string = f'index; {restaurant_list[i]}; {address_list[i]}; {category_list[i]}; {price_list[i]}; {phone_list[i]}; {cuisine_list[i]}; {dietary_list[i]}\n'
                else:
                    string = f'{i-1}; {restaurant_list[i]}; {address_list[i]}; {category_list[i]}; {price_list[i]}; {phone_list[i]}; {cuisine_list[i]}; {dietary_list[i]}\n'
                # string = f'{dietary_list[i]}\n'
                # string += '},\n'
                f.write(string)
                # f.write('\n')
        
       
        f.close()
        # with open('APIvals.csv', 'a') as file:
        #     writer = csv.writer(file)
    
        #     # for i in range(len(cuisine_list)):
        #     #     string = '{'
        #     #     string += f'"restaurant": "{cuisine_list[i]}", "address": "{address_list[i]}"'
        #     #     string += '},'
        #         # print(string)
        #     writer.writerow(cuisine_list[0])
        #     writer.writerow('\n')

    else:

        payload = f"offset={index}&language=en_UK&limit=20500&location_id=186338&currency=GBP"
        response = requests.request("POST", url, data=payload, headers=header)
        
        data = json.loads(response.text)['results']['data']
        for i in range(len(data)):
            # index = str(i)
            # print(data[index]['cuisine'])
            restaurant = data[i]['name']
            address = data[i]['address_obj']['street1']
            category = data[i]['category']['name']
            cuisine = data[i]['cuisine']
            try:
                price = data[i]['price']
                phone_number = data[i]['phone']
            except KeyError:
                price = data[i]['price_level']
                phone_number = 'NULL'
         
            if restaurant not in restaurant_list:
                address_list.append(address)
                restaurant_list.append(restaurant)
                category_list.append(category)
                phone_list.append(phone_number)
                price_list.append(price)
                cuisine_temp_list = []
                dietary_temp_list = []
                for i in range(len(cuisine)-1):
                  
                    if cuisine[i]['name'] not in dietary_reqs:
                        cuisine_temp_list.append(cuisine[i]['name'])
                    else:
                        dietary_temp_list.append(cuisine[i]['name'])

                cuisine_list.append(cuisine_temp_list)
                dietary_list.append(dietary_temp_list)
                # temp_list = []
            
            
                # for i in range(len(cuisine)):
                #     temp[]
                #     dietary_list.append(i['name'])
                    # print(i['name'])
                


        get_API_values(url, header, index+1)


get_API_values(url2, headers, index2)

#     for cuisine in cuisines:

#             cuisine_list.append(cuisine['name'])

        # string=''
    
    # print('{cuisine: {csn}},').format(csn = cuisine_list[i])

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [3]:
import numpy as np
import difflib
import sklearn
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
df = pd.read_excel("APIvals.xlsx", index_col = None)
df
# import pip
# pip3 install sklearn

,index,restaurants,address,category,price,phone No,cuisine,dietary requirements
0,0,Devine Restaurant Coffee Bar,19 Vine Street,Restaurant,8,+44 20 7488 9929,"['Cafe', 'European', 'British']","['Vegan Options', 'Gluten Free Options']"
1,1,Bonoo Indian Tapas,675 Finchley Road,Restaurant,31,+44 20 7794 8899,"['Wine Bar', 'Indian', 'Contemporary', 'Street...","['Vegetarian Friendly', 'Vegan Options']"
2,2,Nora Cafe,9 Wentworth Street,Restaurant,5,+44 20 7247 4992,"['Cafe', 'British', 'Grill']",['Vegetarian Friendly']
3,3,Hibox,48 Goodge Street,Restaurant,9,+44 20 7580 9312,"['Lebanese', 'Mediterranean', 'Middle Eastern'...","['Vegetarian Friendly', 'Vegan Options', 'Halal']"
4,4,Indian Room,59 Bedford Hill,Restaurant,0,NaN,['Indian'],"['Vegetarian Friendly', 'Vegan Options', 'Halal']"
...,...,...,...,...,...,...,...,...
95,95,Smith & Whistle,The Park Lane,Restaurant,13,+44 20 7499 6321,"['Bar', 'British']",['Vegetarian Friendly']
96,96,Daphne Restaurant,83 Bayham Street,Restaurant,0,NaN,"['Mediterranean', 'Greek']","['Vegetarian Friendly', 'Vegan Options']"
97,97,Sitara,784 Holloway Road,Restaurant,0,NaN,['Indian'],"['Vegetarian Friendly', 'Vegan Options', 'Halal']"
98,98,Oi Vita Pizzeria,67 Newington Green Road,Restaurant,11,+44 20 3302 8700,"['Italian', 'Pizza', 'Mediterranean', 'Europea...","['Vegetarian Friendly', 'Vegan Options']"
99,99,Magic Falafel,"Unit 312-313, Camden Market",Restaurant,0,NaN,"['Fast food', 'Mediterranean', 'Middle Eastern']","['Vegetarian Friendly', 'Vegan Options', 'Halal']"

In [4]:
# Address change from postcode to text descriptor
# add jageh ka link
# df
# selected_features = ['cuisine','dietary requirements', 'price', 'address']

# df['dietary requirements'] = df['dietary requirements'].fillna('')
combined_features = df['cuisine'] + ' ' + str(df['price']) + ' ' + df['dietary requirements'] + ' ' + df['address']
print(combined_features) 
# df.head()

0     ['Cafe', 'European', 'British'] 0      8\n1   ...
1     ['Wine Bar', 'Indian', 'Contemporary', 'Street...
2     ['Cafe', 'British', 'Grill'] 0      8\n1     3...
3     ['Lebanese', 'Mediterranean', 'Middle Eastern'...
4     ['Indian'] 0      8\n1     31\n2      5\n3    ...
                            ...
95    ['Bar', 'British'] 0      8\n1     31\n2      ...
96    ['Mediterranean', 'Greek'] 0      8\n1     31\...
97    ['Indian'] 0      8\n1     31\n2      5\n3    ...
98    ['Italian', 'Pizza', 'Mediterranean', 'Europea...
99    ['Fast food', 'Mediterranean', 'Middle Eastern...
Length: 100, dtype: object

In [5]:
vectorizer = TfidfVectorizer()

In [6]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [7]:
print(feature_vectors)

  (0, 264)	0.21970261128095517
  (0, 277)	0.428421929686307
  (0, 20)	0.368088516162276
  (0, 150)	0.3931291452342462
  (0, 162)	0.3931291452342462
  (0, 225)	0.212501102611942
  (0, 275)	0.10733184119230947
  (0, 184)	0.08704271649102258
  (0, 139)	0.08704271649102258
  (0, 1)	0.08704271649102258
  (0, 207)	0.08704271649102258
  (0, 242)	0.08704271649102258
  (0, 218)	0.08704271649102258
  (0, 86)	0.08704271649102258
  (0, 3)	0.08704271649102258
  (0, 85)	0.08704271649102258
  (0, 84)	0.08704271649102258
  (0, 83)	0.08704271649102258
  (0, 12)	0.08704271649102258
  (0, 82)	0.08704271649102258
  (0, 34)	0.08704271649102258
  (0, 109)	0.21970261128095517
  (0, 143)	0.20516176995095187
  (0, 115)	0.26549518347498285
  (1, 245)	0.1686962687367486
  :	:
  (99, 274)	0.3551747989036602
  (99, 173)	0.18214014123286915
  (99, 145)	0.23215837449945154
  (99, 140)	0.22587954155722123
  (99, 217)	0.22587954155722123
  (99, 214)	0.17291555001362785
  (99, 152)	0.08128828684795932
  (99, 276)	0.08128828684795932
  (99, 148)	0.220103575159335
  (99, 225)	0.0880849358508163
  (99, 275)	0.08898135802560561
  (99, 184)	0.07216105708772583
  (99, 139)	0.07216105708772583
  (99, 1)	0.07216105708772583
  (99, 207)	0.07216105708772583
  (99, 242)	0.07216105708772583
  (99, 218)	0.07216105708772583
  (99, 86)	0.07216105708772583
  (99, 3)	0.07216105708772583
  (99, 85)	0.07216105708772583
  (99, 84)	0.07216105708772583
  (99, 83)	0.07216105708772583
  (99, 12)	0.07216105708772583
  (99, 82)	0.07216105708772583
  (99, 34)	0.07216105708772583